<?php

function commerce_bulk_edit_menu() {
  $items['admin/bulk-edit-products'] = array(
    'title' => 'Bulk Edit Products', //page title
    'description' => 'Bulk edit product form',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('commerce_bulk_edit_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return $items;
}

function commerce_bulk_edit_form($form, &$form_state) {
  $form['commerce_product_displays'] = array(
    '#title' => t('Product Display') ,
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => commerce_product_display_options(),
	'#ajax' => array(
	  'callback' => 'commerce_product_displays_ajax',
	  'wrapper' => 'cbe-preview',
	  'method' => 'replace',
	  'effect' => 'fade',
	),
  );
  $form['product_preview'] = array(
    '#title' => t("Product Preview"),
    // The prefix/suffix provide the div that we're replacing, named by
    // #ajax['wrapper'] above.
    '#prefix' => '<div id="cbe-preview">',
    '#suffix' => '</div>',
    '#type' => 'markup',
    '#description' => t('This is my markup field'),
  );
  
  $form['fox_wrapper']['#markup'] = t('The quick @color fox jumps over the lazy dog.', array('@color' => $form_state['values']['fox_color']));


  
  
  
  
  
  
  
  
  
  
  
  
  
  $form['commerce_bulk_edit_image'] = array(
    '#title' => t('Image'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded image will be displayed on this page using the image style choosen below.'),
    '#default_value' => '',
    '#upload_location' => 'public://bulk_edit_products/',
  );
  $form['commerce_bulk_edit_price'] = array(
    '#title' => t('Price') ,
    '#type' => 'textfield',
    '#required' => FALSE,
	'#size' => 30,
  );
  $form['submit'] = array(
    '#type' => 'submit',
	'#value' => 'Submit',
  );
  return $form;
}

function commerce_product_displays_ajax($form, &$form_state) {
  return $form['product_preview'];
}

function commerce_bulk_edit_form_submit($form, &$form_state) {
    dpm($form_state);
    //loading product displays based on selected ID
	$product_display = node_load($form_state['values']['commerce_product_displays']);
	$pids = array();
	foreach ($product_display->field_product[LANGUAGE_NONE] as $key=>$value) {
	$pids[] = $value['product_id'];
	}
	//file
	$file = file_load($form_state['values']['commerce_bulk_edit_image']);
    //loading products
	$products = entity_load('commerce_product', $pids);
	//saving products
    foreach($products as $product){
	if ($form_state['values']['commerce_bulk_edit_price'] !== 0) {
       $product->commerce_price[LANGUAGE_NONE][0]['amount'] = $form_state['values']['commerce_bulk_edit_price']*100;
	}
	if ($form_state['values']['commerce_bulk_edit_image'] !== 0) {
	   $product->field_image[LANGUAGE_NONE][0]['fid'] = $file->fid;
	   $product->field_image[LANGUAGE_NONE][0]['uid'] = $file->uid;
	   $product->field_image[LANGUAGE_NONE][0]['filename'] = $file->filename;
	   $product->field_image[LANGUAGE_NONE][0]['uri'] = $file->uri;
	   $product->field_image[LANGUAGE_NONE][0]['filemime'] = $file->filename;
	   $product->field_image[LANGUAGE_NONE][0]['filesize'] = $file->filesize;
	   $product->field_image[LANGUAGE_NONE][0]['status'] = $file->status;
	   $product->field_image[LANGUAGE_NONE][0]['timestamp'] = $file->timestamp;
	   $product->field_image[LANGUAGE_NONE][0]['rdf_mapping'] = $file->rdf_mapping;
	}
       commerce_product_save($product);
    } 
}
/*
* Select Options callback
*/

function commerce_product_display_options() {
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	->entityCondition('bundle', 'product_display');
	$entity_type = 'node';
	$result = $query->execute();	
	if (!empty($result[$entity_type])) {
	$entities = entity_load($entity_type, array_keys($result[$entity_type]));
	}
	$nodes = entity_load('node', array_keys($result['node']));
    $select_options = array();
    foreach($nodes as $product_displays) {
      $select_options[$product_displays->nid] = $product_displays->title;
    }

    return $select_options;	
}